# we can validate our .yml config
# gem install travis --no-rdoc --no-ri
# travis lint [path to your .travis.yml]

# we'll try to use container based infrastructure
sudo: false
# sudo: required

language: java

jdk:
  - oraclejdk9
    
git:
  depth: 1

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/